In [1]:
import numpy as np


In [2]:
lst = [1,2,3,4,5]
print(lst)
print(type(lst))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
arr = np.array(lst)
print(arr)
print(type(arr))

In [ ]:
arr = np.array([1,2,3,4,5])
arr

In [ ]:
arr = np.zeros(2)
arr

In [ ]:
arr=np.arange(4)
arr

In [ ]:
lst = list(range(0,10))
print(lst)
print(type(lst))

In [ ]:
arr =np.ones(5)
arr

In [ ]:
np.linspace(1,10,5)

In [ ]:
np.ones(45)

In [3]:
arr = np.arange(0,30)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr.reshape(5,6)

In [ ]:
arr,arr.reshape(5,6)

In [ ]:
arr.reshape(10,3)

In [ ]:
np.random.randint(1,5,10)

In [ ]:
np.random.random(10)

In [ ]:
np.random.random((5,2,6))

In [ ]:
arr = np.arange(60).reshape(12,5)
print(arr)

In [5]:
print("array",arr.shape)
print("array size",arr.size)
print("type of array ",arr.dtype)
print("max",arr.max())
print("min",arr.min())
print("mean",arr.mean())
print("sum",arr.sum())

array (30,)
array size 30
type of array  int64
max 29
min 0
mean 14.5
sum 435


In [6]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr.T.shape

In [ ]:
arr[0][1]

In [ ]:
arr

In [ ]:
arr[1][0:2]

In [ ]:
#1,6,11,16
arr[0:5 ,1:2]

In [ ]:
arr[11,4]

In [ ]:
arr[11:12,4:5]

In [ ]:
arr = np.arange(225).reshape(5,15,3)

arr


In [ ]:
arr.ndim, arr.shape,arr.size,arr.dtype

In [ ]:
arr[0]

In [ ]:
arr[:,0,:]

In [ ]:
arr[:,0:1,0]

In [ ]:
arr[0][3][2]==200

In [ ]:
arr[0][3][2]

In [ ]:
arr[0]

In [ ]:
arr=np.array([3,2,5,1,0])


In [ ]:
arr.sort()
arr

In [ ]:
arr+2

In [ ]:
arr-2

In [ ]:
arr*2

In [ ]:
arr/arr

In [ ]:
arr/2

In [ ]:
arr**2

In [ ]:
arr1=np.array([3,2,5,1,0])
arr2=np.array([3,2,5,1,0])

# arr1+arr2
arr**2